version: '3'
services:
  db-api:
    image: "mariadb:bionic"
    ports:
      - "9306:3306"
    env_file: mysql.env
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
  api:
    build: .
    ports: 
      - "9080:8080"
    env_file: api.env
    links:
      - db-api
    volumes:
      - ./node_modules:/usr/src/app/node_modules:cached
      - ./src:/usr/src/app/src:cached
      - ./package.json:/usr/src/app/package.json:cached
      - ./package-lock.json:/usr/src/app/package-lock.json:cached